#!/bin/bash

# This is for tmux based remote-ssh dev users, and it does the following:
# . Binds 'Esc+x' key-combo to help invoke tmux from non-tmux bash
# . Enables sourcing etmux.conf in ${HOME}/.tmux.conf
# . Forces default shell startup in tmux window always (can be exited by ctrl-d).
#   To disable/re-enable etmux auto-launch per each bash session, use below commands:
#    $ etmuxdis # to disable
#    $ etmuxen  # to enable
# . If enabled, tmux can be either:
#   a. first-available previously detached-tmux session, re-attached automatically OR
#   b. new tmux session if there's no prev detached tmux session
if [ ! -f ${HOME}/.disable-etmux ]; then
	wtmux () {
		local sessions=$(tmux ls 2>/dev/null| grep -v "attached")
		if [ -n "${sessions}" ] && [ $(echo ${sessions} | wc -l) -gt 0 ]; then
			tmux attach -t $(echo ${sessions} | head -n1 | cut -d':' -f1)
		else
			tmux
		fi
	}
	if [ -z "$TMUX" ]; then
		# Shortcut 'Esc+x' to launch tmux
		bind -x '"\ex":"wtmux"'
		# If there's any prev detached tmux session, attach it
		# Else, start a fresh tmux session
		wtmux
	else
		# bash started in tmux, 'reset' tty to fix input/output issue
		reset
	fi
fi
